### ISSUE TITLE
Bluebird promise warning

### ISSUE THREAD

**Issue by dvonlehman** [timdp/winston-aws-cloudwatch#2]
I'm getting the warning:

```
Warning: a promise was created in a handler but was not returned from it
    at Bottleneck.schedule (/Users/xakg/src/nordstrom/winston-aws-cloudwatch/node_modules/bottleneck/lib/Bottleneck.js:137:14)
    at Relay._scheduleSubmission (relay.js:39:19)
    at relay.js:52:24
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at Relay._submit (relay.js:52:8)
    at Object.<anonymous> (relay.js:39:39)
    at Object.wrapped (/Users/xakg/src/nordstrom/winston-aws-cloudwatch/node_modules/bottleneck/lib/Bottleneck.js:127:22)
    at [object Object]._onTimeout (/Users/xakg/src/nordstrom/winston-aws-cloudwatch/node_modules/bottleneck/lib/Bottleneck.js:88:32)
    at Timer.listOnTimeout (timers.js:92:15)
```

Not sure if this would be a fix in Bottleneck or winston-aws-cloudwatch. The warning itself emanates from Bluebird: http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it

Logging is working fine, but would be great to eliminate this extra noise.

**Comment by timdp** [comment]
Couldn't agree more. :+1:
